---
- name: Set up production env
  hosts: prod
  remote_user: despair
  become: yes
  tasks:
    - name: Check installed packages
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - mariadb-server
          - firewalld
        state: latest
    - name: start firewalld service and enable it
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - httpd
        - mariadb
    - name: Config firewalld to allow connections to httpd ports
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
    - name: Create webpage content by downloading
      get_url:
        dest: /var/www/html/index.html
        url: http://content.example.com/index.html.j2
        force: yes 
...
