---
- name: using lineinfile module
  hosts: prod
  remote_user: despair
  become: yes
  tasks:
    - name: replace or insert a line
      copy:
        dest: /tmp/multi.txt
        content: |
          line1
          lin2
          lin3
