---
- name: Stop service httpd
  hosts: prod
  remote_user: despair
  become: yes
  tasks:
    - name: Do it
      service:
        name: httpd
        state: stopped
- name: Start 
  hosts: prod
  remote_user: despair
  become: yes
  tasks:
    - name: Do it
      service:
        name: httpd
        state: started
        enabled: yes
      delegate_to: localhost
      become: false

...
