---
- name: Stop service httpd
  hosts: all
  remote_user: despair
  become: yes
  tasks:
    - name: Do it
      service:
        name: httpd
        state: stopped
      delegate_to: localhost
      become: false
...
