- name: Install firewalld
  yum:
    name: firewalld
    state: latest
- name: Start and enable firewalld
  service: 
    name: firewalld
    state: started
    enabled: yes
    immediate: yes
    permanent: yes
- name: Configure firewalld
  firewalld:
    service: http
    enabled: yes
  
